version: '3.8'

services:
  app:
    container_name: ai-image-gen
    depends_on:
      - mongo
    build:
      context: .
      args:
        PORT: ${PORT}
    image: app:v1
    restart: on-failure
    env_file:
      - ${ENV_FILE}
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${HOST_PORT}
    volumes:
      - .m2:/root/.m2
  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    env_file:
      - ${ENV_FILE}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - '27017:27017'
    volumes:
      - db:data/db
